version: 0.2

phases:
  install:
    commands:
      # install terraform binary
      # - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      # - unzip terraform_install.zip -d /usr/bin/
      # - chmod +x /usr/bin/terraform
      - sudo dnf install -y dnf-plugins-core
      - sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
      - sudo dnf -y install terraform
    finally:
      - terraform --version
      - terraform --help
  pre_build:
    commands:
      - terraform -chdir="./terraform/test_env/" init
      - terraform -chdir="./terraform/test_env/" validate
  build:
    commands:
      - terraform -chdir="./terraform/test_env/" apply -auto-approve
  post_build:
    commands:
      - echo Entered the post_build phase...