version: 0.2

phases:
  install:
    commands:
      # install terraform binary
      # - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      # - unzip terraform_install.zip -d /usr/bin/
      # - chmod +x /usr/bin/terraform
      - sudo yum install -y yum-utils shadow-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
    finally:
      - terraform --version
      - terraform --help
      - echo *******************************************WAIT***WAIT***WAIT***********************************
      - pwd
      - ls -a
  pre_build:
    commands:
      - terraform -chdir="./terraform/test_env/" init
      - terraform -chdir="./terraform/test_env/" validate
  build:
    commands:
      - terraform -chdir="./terraform/test_env/" apply -auto-approve
  post_build:
    commands:
      - |
        if [ $? == 1 ]; then
          terraform -chdir="./terraform/test_env/" destroy -auto-approve;
        fi